// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SeanRaw.Web.Data;

#nullable disable

namespace SeanRaw.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SeanRaw.Web.Models.Album", b =>
                {
                    b.Property<int>("IdAlbum")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_album");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAlbum"));

                    b.Property<int>("IdBooking")
                        .HasColumnType("integer")
                        .HasColumnName("id_booking");

                    b.Property<string>("MaTruyCap")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ma_truy_cap_bao_mat");

                    b.Property<string>("ThuMucAnhSuaUrl")
                        .HasColumnType("text")
                        .HasColumnName("thu_muc_anh_sua_url");

                    b.Property<string>("ThuMucAnhThoUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thu_muc_anh_tho_url");

                    b.Property<short>("TrangThaiMoKhoa")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai_mo_khoa");

                    b.HasKey("IdAlbum");

                    b.HasIndex("IdBooking")
                        .IsUnique();

                    b.ToTable("albums", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.AuditLog", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_log");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLog"));

                    b.Property<string>("DiaChiIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("dia_chi_ip");

                    b.Property<string>("DoiTuongBiTacDong")
                        .HasColumnType("text")
                        .HasColumnName("doi_tuong_bi_tac_dong");

                    b.Property<string>("HanhVi")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("hanh_vi");

                    b.Property<string>("IdDoiTuong")
                        .HasColumnType("text")
                        .HasColumnName("id_doi_tuong");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("ThietBiDauCuoi")
                        .HasColumnType("text")
                        .HasColumnName("thiet_bi_dau_cuoi");

                    b.Property<DateTime>("ThoiGianThaoTac")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("thoi_gian_thao_tac");

                    b.HasKey("IdLog");

                    b.HasIndex("IdNguoiDung");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Booking", b =>
                {
                    b.Property<int>("IdBooking")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_booking");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdBooking"));

                    b.Property<string>("DiaDiemChup")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dia_diem_chup");

                    b.Property<int>("IdGoiDichVu")
                        .HasColumnType("integer")
                        .HasColumnName("id_goi_dich_vu");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_khach_hang");

                    b.Property<string>("IdPhotographer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_photographer");

                    b.Property<string>("KhungGioChup")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("khung_gio_chup");

                    b.Property<DateOnly>("NgayChupThucTe")
                        .HasColumnType("date")
                        .HasColumnName("ngay_chup_thuc_te");

                    b.Property<decimal>("TienDaDatCoc")
                        .HasColumnType("numeric")
                        .HasColumnName("tien_da_dat_coc");

                    b.Property<decimal>("TongTienHopDong")
                        .HasColumnType("numeric")
                        .HasColumnName("tong_tien_hop_dong");

                    b.Property<string>("TrangThaiBooking")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trang_thai_booking");

                    b.HasKey("IdBooking");

                    b.HasIndex("IdGoiDichVu");

                    b.HasIndex("IdKhachHang");

                    b.HasIndex("IdPhotographer");

                    b.ToTable("bookings", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.OrderItem", b =>
                {
                    b.Property<int>("IdChiTiet")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_chi_tiet");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdChiTiet"));

                    b.Property<decimal>("GiaGiaoDich")
                        .HasColumnType("numeric")
                        .HasColumnName("gia_giao_dich");

                    b.Property<int>("IdDonHang")
                        .HasColumnType("integer")
                        .HasColumnName("id_don_hang");

                    b.Property<int>("IdSanPham")
                        .HasColumnType("integer")
                        .HasColumnName("id_san_pham");

                    b.Property<int>("SoLuongMua")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong_mua");

                    b.HasKey("IdChiTiet");

                    b.HasIndex("IdDonHang");

                    b.HasIndex("IdSanPham");

                    b.ToTable("order_items", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.PhotographerProfile", b =>
                {
                    b.Property<int>("IdHoSo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_ho_so");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHoSo"));

                    b.Property<string>("AnhChupCanCuoc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("anh_chup_can_cuoc");

                    b.Property<double>("DiemUyTinTrungBinh")
                        .HasColumnType("double precision")
                        .HasColumnName("diem_uy_tin_trung_binh");

                    b.Property<string>("GioiThieuPhongCach")
                        .HasColumnType("text")
                        .HasColumnName("gioi_thieu_phong_cach");

                    b.Property<string>("IdNguoiDung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("SoCanCuocCongDan")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_can_cuoc_cong_dan");

                    b.Property<decimal>("SoDuViTien")
                        .HasColumnType("numeric")
                        .HasColumnName("so_du_vi_tien");

                    b.Property<string>("TrangThaiXacThuc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trang_thai_xac_thuc");

                    b.HasKey("IdHoSo");

                    b.HasIndex("IdNguoiDung")
                        .IsUnique();

                    b.ToTable("photographer_profiles", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Product", b =>
                {
                    b.Property<int>("IdSanPham")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_san_pham");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSanPham"));

                    b.Property<decimal>("GiaBanNiemYet")
                        .HasColumnType("numeric")
                        .HasColumnName("gia_ban_niem_yet");

                    b.Property<string>("HangMayTuongThich")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("hang_may_tuong_thich");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<int>("SoLuongTonKho")
                        .HasColumnType("integer")
                        .HasColumnName("so_luong_ton_kho");

                    b.Property<string>("TenSanPham")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ten_san_pham");

                    b.Property<string>("ThongSoChiTiet")
                        .HasColumnType("text")
                        .HasColumnName("thong_so_chi_tiet");

                    b.HasKey("IdSanPham");

                    b.ToTable("products", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.QuestionBank", b =>
                {
                    b.Property<int>("IdCauHoi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_cau_hoi");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdCauHoi"));

                    b.Property<string>("DapAnDungChuoi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dap_an_dung_chuoi");

                    b.Property<string>("DoKhoCauHoi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("do_kho_cau_hoi");

                    b.Property<string>("LoaiCauHoi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("loai_cau_hoi");

                    b.Property<string>("NoiDungCauHoi")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("noi_dung_cau_hoi");

                    b.HasKey("IdCauHoi");

                    b.ToTable("question_bank", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Review", b =>
                {
                    b.Property<int>("IdDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_danh_gia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDanhGia"));

                    b.Property<int>("IdBooking")
                        .HasColumnType("integer")
                        .HasColumnName("id_booking");

                    b.Property<DateTime>("NgayTaoPhanHoi")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao_phan_hoi");

                    b.Property<string>("NoiDungNhanXet")
                        .HasColumnType("text")
                        .HasColumnName("noi_dung_nhan_xet");

                    b.Property<short>("SoSaoChatLuong")
                        .HasColumnType("smallint")
                        .HasColumnName("so_sao_chat_luong");

                    b.HasKey("IdDanhGia");

                    b.HasIndex("IdBooking")
                        .IsUnique();

                    b.ToTable("reviews", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.SelectedPhoto", b =>
                {
                    b.Property<int>("IdAnhChon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_anh_chon");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAnhChon"));

                    b.Property<int>("AlbumIdAlbum")
                        .HasColumnType("integer");

                    b.Property<int>("IdAlbum")
                        .HasColumnType("integer")
                        .HasColumnName("id_album");

                    b.Property<DateTime>("NgayChon")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_chon");

                    b.Property<string>("TenFileAnh")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ten_file_anh");

                    b.HasKey("IdAnhChon");

                    b.HasIndex("AlbumIdAlbum");

                    b.ToTable("selected_photos", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.ServicePackage", b =>
                {
                    b.Property<int>("IdGoiDichVu")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_goi_dich_vu");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGoiDichVu"));

                    b.Property<decimal>("GiaTien")
                        .HasColumnType("numeric")
                        .HasColumnName("gia_tien");

                    b.Property<string>("MoTaQuyenLoi")
                        .HasColumnType("text")
                        .HasColumnName("mo_ta_quyen_loi");

                    b.Property<int>("SoAnhDuocSua")
                        .HasColumnType("integer")
                        .HasColumnName("so_anh_duoc_sua");

                    b.Property<string>("TenGoi")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("ten_goi");

                    b.HasKey("IdGoiDichVu");

                    b.ToTable("service_packages", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.StoreOrder", b =>
                {
                    b.Property<int>("IdDonHang")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_don_hang");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDonHang"));

                    b.Property<string>("DiaChiGiaoHang")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("dia_chi_giao_hang");

                    b.Property<string>("IdKhachHang")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("id_khach_hang");

                    b.Property<DateTime>("NgayDatHang")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_dat_hang");

                    b.Property<decimal>("TongTienHoaDon")
                        .HasColumnType("numeric")
                        .HasColumnName("tong_tien_hoa_don");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trang_thai_thanh_toan");

                    b.HasKey("IdDonHang");

                    b.HasIndex("IdKhachHang");

                    b.ToTable("store_orders", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.User", b =>
                {
                    b.Property<string>("IdNguoiDung")
                        .HasColumnType("text")
                        .HasColumnName("id_nguoi_dung");

                    b.Property<string>("DiaChiEmail")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("dia_chi_email");

                    b.Property<string>("HoTenDayDu")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ho_ten_day_du");

                    b.Property<string>("MatKhauBam")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("mat_khau_bam");

                    b.Property<DateTime>("NgayTaoTaiKhoan")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngay_tao_tai_khoan");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("so_dien_thoai");

                    b.Property<string>("TenDangNhap")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("ten_dang_nhap");

                    b.Property<short>("TrangThaiTaiKhoan")
                        .HasColumnType("smallint")
                        .HasColumnName("trang_thai_tai_khoan");

                    b.Property<string>("VaiTroNguoiDung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vai_tro_nguoi_dung");

                    b.HasKey("IdNguoiDung");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Album", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.Booking", "Booking")
                        .WithOne("Album")
                        .HasForeignKey("SeanRaw.Web.Models.Album", "IdBooking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.AuditLog", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("IdNguoiDung")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Booking", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.ServicePackage", "ServicePackage")
                        .WithMany("Bookings")
                        .HasForeignKey("IdGoiDichVu")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeanRaw.Web.Models.User", "KhachHang")
                        .WithMany("BookingsAsClient")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SeanRaw.Web.Models.User", "Photographer")
                        .WithMany()
                        .HasForeignKey("IdPhotographer")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");

                    b.Navigation("Photographer");

                    b.Navigation("ServicePackage");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.OrderItem", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.StoreOrder", "StoreOrder")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdDonHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SeanRaw.Web.Models.Product", "Product")
                        .WithMany("OrderItems")
                        .HasForeignKey("IdSanPham")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");

                    b.Navigation("StoreOrder");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.PhotographerProfile", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.User", "User")
                        .WithOne("PhotographerProfile")
                        .HasForeignKey("SeanRaw.Web.Models.PhotographerProfile", "IdNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Review", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.Booking", "Booking")
                        .WithOne("Review")
                        .HasForeignKey("SeanRaw.Web.Models.Review", "IdBooking")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.SelectedPhoto", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.Album", "Album")
                        .WithMany("SelectedPhotos")
                        .HasForeignKey("AlbumIdAlbum")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Album");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.StoreOrder", b =>
                {
                    b.HasOne("SeanRaw.Web.Models.User", "KhachHang")
                        .WithMany("StoreOrders")
                        .HasForeignKey("IdKhachHang")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("KhachHang");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Album", b =>
                {
                    b.Navigation("SelectedPhotos");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Booking", b =>
                {
                    b.Navigation("Album");

                    b.Navigation("Review");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.Product", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.ServicePackage", b =>
                {
                    b.Navigation("Bookings");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.StoreOrder", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("SeanRaw.Web.Models.User", b =>
                {
                    b.Navigation("BookingsAsClient");

                    b.Navigation("PhotographerProfile");

                    b.Navigation("StoreOrders");
                });
#pragma warning restore 612, 618
        }
    }
}
